name: checkout
on: workflow_dispatch # 사용자가 원할때 트리거

jobs:
  # no-checkout잡은 Checkout을 수행하지 않고 cat README.md 시도
  no-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: check file list
        run: cat README.md

  # no-checkout잡은 Checkout을 수행한 뒤 cat README.md 시도
  checkout:
      runs-on: ubuntu-latest
      steps:
        # 1번째 step(use checkout action): 레포지토리 코드 읽어오기
        - name: use checkout action
          uses: actions/checkout@v4 
          # uses를 통해 다른이가 만들어 놓은 액션을 가져와 실행(import 같은 개념)
          # 그중에서도 actions/checkout@v4는 레포지토리의 코드를 가져오는 액션을 취함

        # 2번째 step(check file list): README.md 읽어오기
        - name: check file list
          run: cat README.md